insert into tb_category (name, status) values ('Administração, Negócios e Economia', true)
insert into tb_category (name, status) values ('Arte, Cinema e Fotografia', true)
insert into tb_category (name, status) values ('Artesanato, Casa e Estilo de Vida', true)
insert into tb_category (name, status) values ('Autoajuda', true)
insert into tb_category (name, status) values ('Biografias e Histórias Reais', true)
insert into tb_category (name, status) values ('Ciências', true)
insert into tb_category (name, status) values ('Computação, Informática e Mídias Digitais', true)
insert into tb_category (name, status) values ('Crônicas, Humor e Entretenimento', true)
insert into tb_category (name, status) values ('Direito', true)
insert into tb_category (name, status) values ('Educação, Referência e Didáticos', true)
insert into tb_category (name, status) values ('Engenharia e Transporte', true)
insert into tb_category (name, status) values ('Erótico', true)
insert into tb_category (name, status) values ('Esportes e Lazer', true)
insert into tb_category (name, status) values ('Fantasia, Horror e Ficção Científica', true)
insert into tb_category (name, status) values ('Gastronomia e Culinária', true)
insert into tb_category (name, status) values ('História', true)
insert into tb_category (name, status) values ('HQs, Mangás e Graphic Novels', true)
insert into tb_category (name, status) values ('Infantil', true)
insert into tb_category (name, status) values ('Jovens e Adolescentes', true)
insert into tb_category (name, status) values ('LGBT', true)
insert into tb_category (name, status) values ('Literatura e Ficção', true)
insert into tb_category (name, status) values ('Medicina', true)
insert into tb_category (name, status) values ('Policial, Suspense e Mistério', true)
insert into tb_category (name, status) values ('Religião e Espiritualidade', true)
insert into tb_category (name, status) values ('Romance', true)
insert into tb_category (name, status) values ('Saúde e Família', true)
insert into tb_category (name, status) values ('Turismo e Guias de Viagem', true)
insert into tb_category (name, status) values ('Inglês e Outras Línguas', true)

insert into tb_image (img_url) values ('https://images.unsplash.com/photo-1471970471555-19d4b113e9ed?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80')

insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')
insert into tb_product (title, description, quantity, status, rating, price, author, publisher, pages, size) values('Código Limpo: Habilidades Práticas do Agile Software Capa comum – 8 setembro 2009', '', 50, true, 4.8,71.99,'Robert C. Martin','Alta Books; 1ª edição (8 setembro 2009)', 456, '24 x 17 x 2.2 cm')

insert into tb_image_product (image_id, product_id) values (1,1)
insert into tb_image_product (image_id, product_id) values (1,2)
insert into tb_image_product (image_id, product_id) values (1,3)
insert into tb_image_product (image_id, product_id) values (1,4)
insert into tb_image_product (image_id, product_id) values (1,5)
insert into tb_image_product (image_id, product_id) values (1,6)
insert into tb_image_product (image_id, product_id) values (1,7)
insert into tb_image_product (image_id, product_id) values (1,8)
insert into tb_image_product (image_id, product_id) values (1,9)
insert into tb_image_product (image_id, product_id) values (1,10)
insert into tb_image_product (image_id, product_id) values (1,11)
insert into tb_image_product (image_id, product_id) values (1,12)
insert into tb_image_product (image_id, product_id) values (1,13)
insert into tb_image_product (image_id, product_id) values (1,14)
insert into tb_image_product (image_id, product_id) values (1,15)
insert into tb_image_product (image_id, product_id) values (1,16)
insert into tb_image_product (image_id, product_id) values (1,17)
insert into tb_image_product (image_id, product_id) values (1,18)
insert into tb_image_product (image_id, product_id) values (1,19)
insert into tb_image_product (image_id, product_id) values (1,20)
insert into tb_image_product (image_id, product_id) values (1,21)
insert into tb_image_product (image_id, product_id) values (1,22)
insert into tb_image_product (image_id, product_id) values (1,23)
insert into tb_image_product (image_id, product_id) values (1,24)
insert into tb_image_product (image_id, product_id) values (1,25)
insert into tb_image_product (image_id, product_id) values (1,26)
insert into tb_image_product (image_id, product_id) values (1,27)
insert into tb_image_product (image_id, product_id) values (1,28)
insert into tb_image_product (image_id, product_id) values (1,29)
insert into tb_image_product (image_id, product_id) values (1,30)
insert into tb_image_product (image_id, product_id) values (1,31)
insert into tb_image_product (image_id, product_id) values (1,32)
insert into tb_image_product (image_id, product_id) values (1,33)
insert into tb_image_product (image_id, product_id) values (1,34)
insert into tb_image_product (image_id, product_id) values (1,35)
insert into tb_image_product (image_id, product_id) values (1,36)
insert into tb_image_product (image_id, product_id) values (1,37)
insert into tb_image_product (image_id, product_id) values (1,38)
insert into tb_image_product (image_id, product_id) values (1,39)
insert into tb_image_product (image_id, product_id) values (1,40)
insert into tb_image_product (image_id, product_id) values (1,41)
insert into tb_image_product (image_id, product_id) values (1,42)
insert into tb_image_product (image_id, product_id) values (1,43)
insert into tb_image_product (image_id, product_id) values (1,44)
insert into tb_image_product (image_id, product_id) values (1,45)
insert into tb_image_product (image_id, product_id) values (1,46)
insert into tb_image_product (image_id, product_id) values (1,47)
insert into tb_image_product (image_id, product_id) values (1,48)
insert into tb_image_product (image_id, product_id) values (1,49)
insert into tb_image_product (image_id, product_id) values (1,50)
insert into tb_image_product (image_id, product_id) values (1,51)
insert into tb_image_product (image_id, product_id) values (1,52)
insert into tb_image_product (image_id, product_id) values (1,53)
insert into tb_image_product (image_id, product_id) values (1,54)
insert into tb_image_product (image_id, product_id) values (1,55)
insert into tb_image_product (image_id, product_id) values (1,56)
insert into tb_image_product (image_id, product_id) values (1,57)
insert into tb_image_product (image_id, product_id) values (1,58)
insert into tb_image_product (image_id, product_id) values (1,59)
insert into tb_image_product (image_id, product_id) values (1,60)


insert into tb_category_product (category_id, product_id) values (1,1)
insert into tb_category_product (category_id, product_id) values (1,2)
insert into tb_category_product (category_id, product_id) values (1,3)
insert into tb_category_product (category_id, product_id) values (1,4)
insert into tb_category_product (category_id, product_id) values (1,5)
insert into tb_category_product (category_id, product_id) values (1,6)
insert into tb_category_product (category_id, product_id) values (1,7)
insert into tb_category_product (category_id, product_id) values (1,8)
insert into tb_category_product (category_id, product_id) values (1,9)
insert into tb_category_product (category_id, product_id) values (1,10)
insert into tb_category_product (category_id, product_id) values (1,11)
insert into tb_category_product (category_id, product_id) values (1,12)
insert into tb_category_product (category_id, product_id) values (1,13)
insert into tb_category_product (category_id, product_id) values (1,14)
insert into tb_category_product (category_id, product_id) values (1,15)
insert into tb_category_product (category_id, product_id) values (1,16)
insert into tb_category_product (category_id, product_id) values (1,17)
insert into tb_category_product (category_id, product_id) values (1,18)
insert into tb_category_product (category_id, product_id) values (1,19)
insert into tb_category_product (category_id, product_id) values (1,20)
insert into tb_category_product (category_id, product_id) values (1,21)
insert into tb_category_product (category_id, product_id) values (1,22)
insert into tb_category_product (category_id, product_id) values (1,23)
insert into tb_category_product (category_id, product_id) values (1,24)
insert into tb_category_product (category_id, product_id) values (1,25)
insert into tb_category_product (category_id, product_id) values (1,26)
insert into tb_category_product (category_id, product_id) values (1,27)
insert into tb_category_product (category_id, product_id) values (1,28)
insert into tb_category_product (category_id, product_id) values (1,29)
insert into tb_category_product (category_id, product_id) values (1,30)
insert into tb_category_product (category_id, product_id) values (1,31)
insert into tb_category_product (category_id, product_id) values (1,32)
insert into tb_category_product (category_id, product_id) values (1,33)
insert into tb_category_product (category_id, product_id) values (1,34)
insert into tb_category_product (category_id, product_id) values (1,35)
insert into tb_category_product (category_id, product_id) values (1,36)
insert into tb_category_product (category_id, product_id) values (1,37)
insert into tb_category_product (category_id, product_id) values (1,38)
insert into tb_category_product (category_id, product_id) values (1,39)
insert into tb_category_product (category_id, product_id) values (1,40)
insert into tb_category_product (category_id, product_id) values (1,41)
insert into tb_category_product (category_id, product_id) values (1,42)
insert into tb_category_product (category_id, product_id) values (1,43)
insert into tb_category_product (category_id, product_id) values (1,44)
insert into tb_category_product (category_id, product_id) values (1,45)
insert into tb_category_product (category_id, product_id) values (1,46)
insert into tb_category_product (category_id, product_id) values (1,47)
insert into tb_category_product (category_id, product_id) values (1,48)
insert into tb_category_product (category_id, product_id) values (1,49)
insert into tb_category_product (category_id, product_id) values (1,50)
insert into tb_category_product (category_id, product_id) values (1,51)
insert into tb_category_product (category_id, product_id) values (1,52)
insert into tb_category_product (category_id, product_id) values (1,53)
insert into tb_category_product (category_id, product_id) values (1,54)
insert into tb_category_product (category_id, product_id) values (1,55)
insert into tb_category_product (category_id, product_id) values (1,56)
insert into tb_category_product (category_id, product_id) values (1,57)
insert into tb_category_product (category_id, product_id) values (1,58)
insert into tb_category_product (category_id, product_id) values (1,59)
insert into tb_category_product (category_id, product_id) values (1,60)